project:
  type: website
  output-dir: docs
  render:
  - index.qmd
  - pages/admin/*.qmd
  - pages/exercises/*.qmd
  - pages/formulas/*.qmd
website:
  title: Statistik 1
  site-url: https://psylu.github.io/statistik1-hs24/
  reader-mode: true
  navbar:
    background: primary
    left:
    - href: index.qmd
    - pages/admin/page_1.qmd
  sidebar:
    style: floating
    search: true
    contents:
    - section: Übungen
      contents:
      - pages/exercises/exercise_01.qmd
      - pages/exercises/exercise_02.qmd
      - pages/exercises/exercise_03.qmd
      - pages/exercises/exercise_04.qmd
      - pages/exercises/exercise_05.qmd
      - pages/exercises/exercise_06.qmd
      - pages/exercises/exercise_08.qmd
      - pages/exercises/exercise_09.qmd
      - pages/exercises/exercise_10.qmd
      - pages/exercises/exercise_11.qmd
      - pages/exercises/exercise_12.qmd
      - pages/exercises/exercise_13.qmd
    - section: R
      contents:
      - pages/exercises/webr.qmd
      - pages/exercises/introduction_to_r.qmd
    - section: Formelsammlung
      contents: pages/formulas/formelsammlung.qmd
format:
  html:
    theme:
      light:
      - flatly
      - styles/light.scss
      dark:
      - darkly
      - styles/dark.scss
    css:
    - styles.css
    - include/webex.css
    toc: true
    link-external-newwindow: true
    include-after-body: include/webex.js
editor:
  render-on-save: true
